title: PhizMusic Wiki
description: Physics-first music theory wiki
url: https://simonseo.github.io
baseurl: /phizmusic/
remote_theme: poole/hyde
markdown: kramdown
permalink: pretty

plugins:
  - jekyll-remote-theme
  - jekyll-relative-links

relative_links:
  enabled: true
  collections: true

include:
  - wiki

exclude:
  - .sisyphus
  - validate.sh
